version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn global add gulp
      - run: yarn build
      - run: tar -cf dist.tar dist
      - store_artifacts:
          path: dist.tar
      - persist_to_workspace:
          root: .
          paths:
            - dist.tar
  
  tslint:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: mkdir -p tests-report/tslint
      - run: yarn tslint --format junit -o tests-report/tslint/tslint.xml
      - store_test_results:
          path: tests-report

  deploy:
    machine: true
    working_directory: ~/repo/dist
    environment:
      # AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID  # Isso está definido nas configurações da build
      # AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY  # Isso está definido nas configurações da build
      AWS_DEFAULT_REGION: us-east-1  # Só mude se necessário
      AWS_S3_BUCKET: pokenet  # Coloque o nome do bucket aqui
    steps:
      - attach_workspace:
          at: .
      - run: |
          docker run -it --rm \
            -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" \
            -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" \
            -e "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" \
            -e "AWS_S3_BUCKET=$AWS_S3_BUCKET" \
            -v "oxe:/pokenet" \
            carlosaschjr/deploy-to-s3

workflows:
  version: 2
  build-then-test-then-deploy:
    jobs:
      - tslint
      - build:
          requires:
            - tslint
      - deploy:
          requires:
            - tslint
            - build