version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
          - node_modules
      - run: yarn global add gulp
      - run: yarn build
      - run: tar -cf dist.tar dist
      - store_artifacts:
          path: ~/repo/dist.tar
  
  tslint:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: mkdir -p tests-report/tslint
      - run: yarn tslint --format junit -o tests-report/tslint/tslint.xml
      - store_test_results:
          path: tests-report

  deployment:
    prod:
      branch: master
      commands:
        - aws s3 sync ~/repo/dist.tar s3://circle-production-static-site/docs/ --delete

workflows:
  version: 2
  build-then-test:
    jobs:
      - tslint
      - build:
          requires:
            - tslint
      - deployment:
          requires:
            -build